/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The category of telemetry event
 */
export type EventType = "track" | "identify" | "error";

/**
 * Canonical schema for Backshift telemetry events
 */
export interface BackshiftEvent {
  /**
   * Array of telemetry events to ingest
   *
   * @minItems 1
   * @maxItems 100
   */
  batch: [BatchedEvent, ...BatchedEvent[]];
}
export interface BatchedEvent {
  type: EventType;
  /**
   * Event name for track events (e.g. 'Checkout_Started')
   */
  event?: string;
  /**
   * User identifier for identify events
   */
  userId?: string;
  /**
   * Arbitrary event properties for track events
   */
  properties?: {
    [k: string]: unknown;
  };
  /**
   * User trait properties for identify events
   */
  traits?: {
    [k: string]: unknown;
  };
  error?: SerializedError;
  context: EventContext;
}
export interface SerializedError {
  /**
   * Error message
   */
  message: string;
  /**
   * Error constructor name (e.g. 'TypeError', 'RangeError')
   */
  name: string;
  /**
   * Stack trace string (may be minified — demangled server-side)
   */
  stack?: string;
}
/**
 * Implicit context automatically attached by the client SDK
 */
export interface EventContext {
  /**
   * Browser viewport dimensions (e.g. '390x844')
   */
  viewport: string;
  /**
   * Current page URL or route path
   */
  url: string;
  /**
   * Anonymous session identifier (prefixed with 'anon_')
   */
  sessionId: string;
  /**
   * Application version or git commit hash
   */
  appVersion: string;
  /**
   * Unix epoch in milliseconds
   */
  timestamp: number;
  /**
   * Client IP address — enriched server-side, stripped before fan-out
   */
  ip?: string;
  /**
   * Browser user-agent string — enriched server-side
   */
  userAgent?: string;
  /**
   * ISO 3166-1 alpha-2 country code — enriched from geo lookup server-side
   */
  country?: string;
  /**
   * document.referrer at the time of the event
   */
  referrer?: string;
  /**
   * document.title at the time of the event
   */
  pageTitle?: string;
  /**
   * UTM source parameter (utm_source)
   */
  utmSource?: string;
  /**
   * UTM medium parameter (utm_medium)
   */
  utmMedium?: string;
  /**
   * UTM campaign parameter (utm_campaign)
   */
  utmCampaign?: string;
  /**
   * UTM term parameter (utm_term)
   */
  utmTerm?: string;
  /**
   * UTM content parameter (utm_content)
   */
  utmContent?: string;
}
